-- 1. Table: LOYALTY_TIER
CREATE TABLE LOYALTY_TIER (
  tier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tier_name VARCHAR(50) NOT NULL,
  points_required INTEGER NOT NULL DEFAULT 0,
  discount_percentage DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
  benefits_description TEXT,
  CONSTRAINT chk_points_positive CHECK (points_required >= 0),
  CONSTRAINT chk_discount_range CHECK (discount_percentage BETWEEN 0 AND 100)
);

-- 2. Table: GUEST
CREATE TABLE GUEST (
  guest_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(100) UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Table: PRIVATE_GUEST
CREATE TABLE PRIVATE_GUEST (
  guest_id INTEGER PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  id_or_passport_number VARCHAR(20) NOT NULL UNIQUE,
  gender VARCHAR(15),
  CONSTRAINT fk_private_guest_id FOREIGN KEY (guest_id) REFERENCES GUEST (guest_id) ON DELETE CASCADE,
  CONSTRAINT chk_gender_type CHECK (gender IN ('Male', 'Female', 'Other'))
);

-- 4. Table: CORPORATE_GUEST
CREATE TABLE CORPORATE_GUEST (
  guest_id INTEGER PRIMARY KEY,
  company_name VARCHAR(100) NOT NULL,
  company_registration_number VARCHAR(50) NOT NULL UNIQUE,
  contact_person_name VARCHAR(100),
  CONSTRAINT fk_corporate_guest_id FOREIGN KEY (guest_id) REFERENCES GUEST (guest_id) ON DELETE CASCADE
);

-- 5. Table: GUEST_LOYALTY
CREATE TABLE GUEST_LOYALTY (
  guest_id INTEGER PRIMARY KEY,
  membership_number VARCHAR(50) UNIQUE NOT NULL,
  points_balance INTEGER DEFAULT 0,
  status VARCHAR(20) DEFAULT 'Active',
  tier_id INTEGER NOT NULL,
  CONSTRAINT fk_loyalty_guest FOREIGN KEY (guest_id) REFERENCES GUEST (guest_id) ON DELETE CASCADE,
  CONSTRAINT fk_loyalty_tier FOREIGN KEY (tier_id) REFERENCES LOYALTY_TIER (tier_id),
  CONSTRAINT chk_points_balance CHECK (points_balance >= 0),
  CONSTRAINT chk_loyalty_status CHECK (status IN ('Active', 'Inactive', 'Suspended'))
);

-- 6. Table: STAY_RECORD
CREATE TABLE STAY_RECORD (
  stay_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  check_in_date DATE NOT NULL,
  check_out_date DATE NOT NULL,
  stay_status VARCHAR(20) DEFAULT 'Booked',
  guest_id INTEGER NOT NULL,
  CONSTRAINT fk_stay_guest FOREIGN KEY (guest_id) REFERENCES GUEST (guest_id) ON DELETE CASCADE,
  CONSTRAINT chk_date_order CHECK (check_out_date >= check_in_date),
  CONSTRAINT chk_stay_status CHECK (
    stay_status IN ('Booked', 'CheckedIn', 'CheckedOut', 'Cancelled')
  )
);

-- 7. Table: PAYMENT
CREATE TABLE PAYMENT (
  payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  amount DECIMAL(10, 2) NOT NULL,
  payment_method VARCHAR(50) DEFAULT 'Credit Card',
  payment_status VARCHAR(20) DEFAULT 'Pending',
  stay_id INTEGER NOT NULL,
  CONSTRAINT fk_payment_stay FOREIGN KEY (stay_id) REFERENCES STAY_RECORD (stay_id) ON DELETE CASCADE,
  CONSTRAINT chk_amount_positive CHECK (amount >= 0),
  CONSTRAINT chk_payment_status CHECK (
    payment_status IN ('Pending', 'Completed', 'Failed', 'Refunded')
  )
);

-- 8. Table: GUEST_FEEDBACK
CREATE TABLE GUEST_FEEDBACK (
  stay_id INTEGER PRIMARY KEY,
  rating INTEGER NOT NULL,
  comments TEXT,
  feedback_date DATE NOT NULL,
  CONSTRAINT fk_feedback_stay FOREIGN KEY (stay_id) REFERENCES STAY_RECORD (stay_id) ON DELETE CASCADE,
  CONSTRAINT chk_rating_range CHECK (rating BETWEEN 1 AND 5)
);