DROP TABLE IF EXISTS GUEST_FEEDBACK;

DROP TABLE IF EXISTS PAYMENT;

DROP TABLE IF EXISTS STAY_RECORD;

DROP TABLE IF EXISTS GUEST_LOYALTY;

DROP TABLE IF EXISTS CORPORATE_GUEST;

DROP TABLE IF EXISTS PRIVATE_GUEST;

DROP TABLE IF EXISTS GUEST;

DROP TABLE IF EXISTS LOYALTY_TIER;